name: Actualizar Catalogo

on:
  workflow_dispatch:

jobs:
  actualizar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: |
          pip install pandas gspread google-auth openpyxl requests beautifulsoup4

      - name: Ejecutar Pasteur
        run: python scraper/scraper_pasteur86.py